export const CATEGORIES_STATE_CHANGE = "CATEGORIES_CHANGE";
export const EXPENSES_STATE_CHANGE = "EXPENSES_STATE_CHANGE";

export default {
  CATEGORIES_STATE_CHANGE,
  EXPENSES_STATE_CHANGE,
};
